# Generated by Django 5.2.8 on 2025-11-15 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالإنجليزية')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('hashed_code', models.CharField(max_length=255, verbose_name='الكود المشفر')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
            ],
            options={
                'verbose_name': 'كود OTP',
                'verbose_name_plural': 'أكواد OTP',
                'db_table': 'OtpCodes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=255, verbose_name='رابط الصورة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='خط الطول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='submissions.category', verbose_name='الفئة')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='submissions.user', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقديم',
                'verbose_name_plural': 'التقديمات',
                'db_table': 'Submissions',
            },
        ),
    ]
