# Generated by Django 5.2.8 on 2025-11-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='consumption_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الاستهلاك'),
        ),
        migrations.AddField(
            model_name='submission',
            name='counter_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم العداد'),
        ),
        migrations.AddField(
            model_name='submission',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/', verbose_name='صورة الفاتورة'),
        ),
    ]
