# Generated by Django 5.2.8 on 2025-11-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_consumption_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='invoice_image',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='صورة الفاتورة'),
        ),
    ]
