# Generated by Django 5.2.8 on 2025-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submission_invoice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/', verbose_name='صورة الفاتورة'),
        ),
    ]
