# Generated by Django 5.2.8 on 2025-11-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submission_invoice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='image_url',
            field=models.ImageField(upload_to='submissions/', verbose_name='صورة التقديم'),
        ),
    ]
