# Generated by Django 5.2.8 on 2025-11-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_submission_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(verbose_name='تاريخ الإنشاء'),
        ),
    ]
